'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateAnnualReexamination

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnCompleteReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCompleteReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeVerification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerVerification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessVerification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeCalculation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerCalculation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessCalculation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypePaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypePaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypePaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypePaymentStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerPaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerPaymentStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusPaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessPaymentStandard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeUtilityAllowance As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUtilityAllowance As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessUtilityAllowance As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeTenantRent As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerTenantRent As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessTenantRent As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeOccupancyStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerOccupancyStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessOccupancyStandard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeAnnualReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeAnnualReexamination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeAnnualReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeAnnualReexamination As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerAnnualReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerAnnualReexamination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerAnnualReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerAnnualReexamination As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusAnnualReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusAnnualReexamination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessAnnualReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessAnnualReexamination As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeChangeInFamilyComposition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeChangeInFamilyComposition As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerChangeInFamilyComposition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerChangeInFamilyComposition As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusChangeInFamilyComposition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessChangeInFamilyComposition As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeDataEntry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDataEntry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessDataEntry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProcessOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProcessOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessOther As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeLease As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeLease As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerLease As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerLease As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLease As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateLease As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHapContract As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHapContract As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHapContract As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHapContract As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHapContract As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHapContract As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHudTenancyAddendum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHudTenancyAddendum As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHudTenancyAddendum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHudTenancyAddendum As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHudTenancyAddendum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHudTenancyAddendum As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeValidPhotoIdentification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeValidPhotoIdentification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerValidPhotoIdentification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerValidPhotoIdentification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusValidPhotoIdentification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateValidPhotoIdentification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProofOfBirthDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProofOfBirthDate As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProofOfBirthDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProofOfBirthDate As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProofOfBirthDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProofOfBirthDate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeVawaClientNotice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeVawaClientNotice As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerVawaClientNotice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerVawaClientNotice As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusVawaClientNotice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateVawaClientNotice As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeSignedOriginalVoucher As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeSignedOriginalVoucher As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerSignedOriginalVoucher As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerSignedOriginalVoucher As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusSignedOriginalVoucher As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateSignedOriginalVoucher As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeCriminalBackgroundScreeningDetermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeCriminalBackgroundScreeningDetermination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeCriminalBackgroundScreeningDetermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeCriminalBackgroundScreeningDetermination As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerCriminalBackgroundScreeningDetermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerCriminalBackgroundScreeningDetermination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerCriminalBackgroundScreeningDetermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerCriminalBackgroundScreeningDetermination As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusCriminalBackgroundScreeningDetermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusCriminalBackgroundScreeningDetermination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateCriminalBackgroundScreeningDetermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateCriminalBackgroundScreeningDetermination As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeCriminalBackgroundScreeningRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeCriminalBackgroundScreeningRequest As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeCriminalBackgroundScreeningRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeCriminalBackgroundScreeningRequest As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerCriminalBackgroundScreeningRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerCriminalBackgroundScreeningRequest As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerCriminalBackgroundScreeningRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerCriminalBackgroundScreeningRequest As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusCriminalBackgroundScreeningRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusCriminalBackgroundScreeningRequest As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateCriminalBackgroundScreeningRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateCriminalBackgroundScreeningRequest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeNotes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeNotes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerNotes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerNotes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusNotes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateNotes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDocumentOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDocumentOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateDocumentOther As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRecertificationChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRecertificationChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRecertificationChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRecertificationChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRecertificationChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRecertificationChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRecertificationChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRecertificationChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRecertificationChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRecertificationChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRecertificationChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRecertificationChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentLetterTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentLetterTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentLetterTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRentLetterTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentLetterTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRentLetterTenant As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentLetterOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentLetterOwner As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentLetterOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRentLetterOwner As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentLetterOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRentLetterOwner As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlHudForm50058 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHudForm50058 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHudForm50058 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentCalculationSheet As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRentCalculationSheet As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRentCalculationSheet As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeEivIncomeReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeEivIncomeReport As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeEivIncomeReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeEivIncomeReport As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerEivIncomeReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerEivIncomeReport As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerEivIncomeReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerEivIncomeReport As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusEivIncomeReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusEivIncomeReport As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateEivIncomeReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateEivIncomeReport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUtilityBillForTenantPaidUtilities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUtilityBillForTenantPaidUtilities As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeUtilityBillForTenantPaidUtilities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeUtilityBillForTenantPaidUtilities As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUtilityBillForTenantPaidUtilities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUtilityBillForTenantPaidUtilities As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUtilityBillForTenantPaidUtilities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUtilityBillForTenantPaidUtilities As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUtilityBillForTenantPaidUtilities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUtilityBillForTenantPaidUtilities As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateUtilityBillForTenantPaidUtilities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateUtilityBillForTenantPaidUtilities As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeFamilyObligations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeFamilyObligations As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeFamilyObligations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeFamilyObligations As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerFamilyObligations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerFamilyObligations As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerFamilyObligations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerFamilyObligations As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusFamilyObligations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusFamilyObligations As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateFamilyObligations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateFamilyObligations As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRecertificationAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRecertificationAppointmentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeRecertificationAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeRecertificationAppointmentLetter As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRecertificationAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRecertificationAppointmentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRecertificationAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRecertificationAppointmentLetter As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRecertificationAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRecertificationAppointmentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRecertificationAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRecertificationAppointmentLetter As Global.System.Web.UI.WebControls.Button
End Class
