'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreatePortIn

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnCompleteReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCompleteReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypePaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypePaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypePaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypePaymentStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerPaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerPaymentStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusPaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessPaymentStandard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeUtilityAllowance As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUtilityAllowance As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessUtilityAllowance As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeTenantRent As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerTenantRent As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessTenantRent As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypePortability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypePortability As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypePortability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypePortability As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerPortability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerPortability As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerPortability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerPortability As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusPortability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusPortability As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessPortability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessPortability As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeDataEntry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDataEntry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessDataEntry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProcessOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProcessOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessOther As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeMasterLeasingChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeMasterLeasingChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerMasterLeasingChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerMasterLeasingChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusMasterLeasingChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateMasterLeasingChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeChecklistLeasingInspections As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeChecklistLeasingInspections As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerChecklistLeasingInspections As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerChecklistLeasingInspections As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusChecklistLeasingInspections As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateChecklistLeasingInspections As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeLeasingPacketChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeLeasingPacketChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerLeasingPacketChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerLeasingPacketChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLeasingPacketChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateLeasingPacketChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeContractsExecutionChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeContractsExecutionChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerContractsExecutionChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerContractsExecutionChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusContractsExecutionChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateContractsExecutionChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeLease As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeLease As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerLease As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerLease As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLease As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateLease As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHapContract As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHapContract As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHapContract As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHapContract As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHapContract As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHapContract As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHudTenancyAddendum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHudTenancyAddendum As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHudTenancyAddendum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHudTenancyAddendum As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHudTenancyAddendum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHudTenancyAddendum As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRfta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeRfta As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRfta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRfta As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRfta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRfta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeSecurityDepositConfirmation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeSecurityDepositConfirmation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerSecurityDepositConfirmation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerSecurityDepositConfirmation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusSecurityDepositConfirmation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateSecurityDepositConfirmation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeInitialRentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeInitialRentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeInitialRentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeInitialRentLetter As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerInitialRentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerInitialRentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerInitialRentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerInitialRentLetter As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusInitialRentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusInitialRentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateInitialRentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateInitialRentLetter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeInitialHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeInitialHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeInitialHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeInitialHudForm50058 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerInitialHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerInitialHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerInitialHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerInitialHudForm50058 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusInitialHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusInitialHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateInitialHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateInitialHudForm50058 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeInitialRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeInitialRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeInitialRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeInitialRentCalculationSheet As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerInitialRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerInitialRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerInitialRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerInitialRentCalculationSheet As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusInitialRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusInitialRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessInitialRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessInitialRentCalculationSheet As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeInitialUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeInitialUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeInitialUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeInitialUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerInitialUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerInitialUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerInitialUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerInitialUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusInitialUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusInitialUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateInitialUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateInitialUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHapContractInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHapContractInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHapContractInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHapContractInitialUnit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHapContractInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHapContractInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHapContractInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHapContractInitialUnit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHapContractInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHapContractInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessHapContractInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessHapContractInitialUnit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHudTenancyAddendumInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHudTenancyAddendumInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHudTenancyAddendumInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHudTenancyAddendumInitialUnit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHudTenancyAddendumInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHudTenancyAddendumInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHudTenancyAddendumInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHudTenancyAddendumInitialUnit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHudTenancyAddendumInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHudTenancyAddendumInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHudTenancyAddendumInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHudTenancyAddendumInitialUnit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeLeaseInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeLeaseInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeLeaseInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeLeaseInitialUnit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerLeaseInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerLeaseInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerLeaseInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerLeaseInitialUnit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusLeaseInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLeaseInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateLeaseInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateLeaseInitialUnit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRftaInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRftaInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeRftaInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeRftaInitialUnit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRftaInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRftaInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRftaInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRftaInitialUnit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRftaInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRftaInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRftaInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRftaInitialUnit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUtilityAllowanceChecklistInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUtilityAllowanceChecklistInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeUtilityAllowanceChecklistInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeUtilityAllowanceChecklistInitialUnit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUtilityAllowanceChecklistInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUtilityAllowanceChecklistInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUtilityAllowanceChecklistInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUtilityAllowanceChecklistInitialUnit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUtilityAllowanceChecklistInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUtilityAllowanceChecklistInitialUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateUtilityAllowanceChecklistInitialUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateUtilityAllowanceChecklistInitialUnit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDocumentOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDocumentOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateDocumentOther As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHapProcessingActionForm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlHapProcessingActionForm As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHapProcessingActionForm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHapProcessingActionForm As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHapProcessingActionForm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHapProcessingActionForm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.Button
End Class
