'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateEligibilityScreening

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnCompleteReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCompleteReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeVerification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerVerification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessVerification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeCalculation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerCalculation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessCalculation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeOccupancyStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerOccupancyStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessOccupancyStandard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeEligibilityAndScreening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeEligibilityAndScreening As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeEligibilityAndScreening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeEligibilityAndScreening As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerEligibilityAndScreening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerEligibilityAndScreening As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerEligibilityAndScreening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerEligibilityAndScreening As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusEligibilityAndScreening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusEligibilityAndScreening As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessEligibilityAndScreening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessEligibilityAndScreening As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeDataEntry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDataEntry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessDataEntry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProcessOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProcessOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessOther As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateMasterFamilyDocumentsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateMasterFamilyDocumentsChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeNewAdmissionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeNewAdmissionChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeNewAdmissionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeNewAdmissionChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerNewAdmissionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerNewAdmissionChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerNewAdmissionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerNewAdmissionChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusNewAdmissionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusNewAdmissionChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateNewAdmissionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateNewAdmissionChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeValidPhotoIdentification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeValidPhotoIdentification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerValidPhotoIdentification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerValidPhotoIdentification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusValidPhotoIdentification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateValidPhotoIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateValidPhotoIdentification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProofOfSocialSecurityNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProofOfSocialSecurityNumber As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProofOfBirthDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProofOfBirthDate As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProofOfBirthDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProofOfBirthDate As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProofOfBirthDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProofOfBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProofOfBirthDate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProofOfNameChangeIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProofOfNameChangeIfApplicable As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProofOfEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProofOfEligibleImmigrationStatus As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateDeclarationOfCitizenshipOrEligibleImmigrationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateDeclarationOfCitizenshipOrEligibleImmigrationStatus As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeCriminalBackgroundScreeningDeterminationInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeCriminalBackgroundScreeningDeterminationInitialIntake As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeCriminalBackgroundScreeningDeterminationInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeCriminalBackgroundScreeningDeterminationInitialIntake As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerCriminalBackgroundScreeningDeterminationInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerCriminalBackgroundScreeningDeterminationInitialIntake As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerCriminalBackgroundScreeningDeterminationInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerCriminalBackgroundScreeningDeterminationInitialIntake As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusCriminalBackgroundScreeningDeterminationInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusCriminalBackgroundScreeningDeterminationInitialIntake As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateCriminalBackgroundScreeningDeterminationInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateCriminalBackgroundScreeningDeterminationInitialIntake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeCriminalBackgroundScreeningRequestInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeCriminalBackgroundScreeningRequestInitialIntake As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeCriminalBackgroundScreeningRequestInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeCriminalBackgroundScreeningRequestInitialIntake As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerCriminalBackgroundScreeningRequestInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerCriminalBackgroundScreeningRequestInitialIntake As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerCriminalBackgroundScreeningRequestInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerCriminalBackgroundScreeningRequestInitialIntake As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusCriminalBackgroundScreeningRequestInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusCriminalBackgroundScreeningRequestInitialIntake As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateCriminalBackgroundScreeningRequestInitialIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateCriminalBackgroundScreeningRequestInitialIntake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeEivExistingTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeEivExistingTenantSearch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeEivExistingTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeEivExistingTenantSearch As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerEivExistingTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerEivExistingTenantSearch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerEivExistingTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerEivExistingTenantSearch As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusEivExistingTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusEivExistingTenantSearch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateEivExistingTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateEivExistingTenantSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeEivFormerTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeEivFormerTenantSearch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeEivFormerTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeEivFormerTenantSearch As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerEivFormerTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerEivFormerTenantSearch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerEivFormerTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerEivFormerTenantSearch As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusEivFormerTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusEivFormerTenantSearch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateEivFormerTenantSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateEivFormerTenantSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886Initial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886Initial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886Initial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886Initial As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886Initial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886Initial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886Initial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886Initial As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusAuthorizationForReleaseOfInformationPrivacyActHud9886Initial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusAuthorizationForReleaseOfInformationPrivacyActHud9886Initial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateAuthorizationForReleaseOfInformationPrivacyActHud9886Initial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateAuthorizationForReleaseOfInformationPrivacyActHud9886Initial As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHanoAuthorizationForReleaseOfInformationInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHanoAuthorizationForReleaseOfInformationInitial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHanoAuthorizationForReleaseOfInformationInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHanoAuthorizationForReleaseOfInformationInitial As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHanoAuthorizationForReleaseOfInformationInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHanoAuthorizationForReleaseOfInformationInitial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHanoAuthorizationForReleaseOfInformationInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHanoAuthorizationForReleaseOfInformationInitial As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHanoAuthorizationForReleaseOfInformationInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHanoAuthorizationForReleaseOfInformationInitial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHanoAuthorizationForReleaseOfInformationInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHanoAuthorizationForReleaseOfInformationInitial As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateDebtsOwedToPhaAndTerminationsHud52675 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateDebtsOwedToPhaAndTerminationsHud52675 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHudSupplementSheetHud92006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHudSupplementSheetHud92006 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeVawaClientNotice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeVawaClientNotice As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerVawaClientNotice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerVawaClientNotice As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusVawaClientNotice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateVawaClientNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateVawaClientNotice As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeSpecialProgramReferralFormIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeSpecialProgramReferralFormIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeSpecialProgramReferralFormIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeSpecialProgramReferralFormIfApplicable As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerSpecialProgramReferralFormIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerSpecialProgramReferralFormIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerSpecialProgramReferralFormIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerSpecialProgramReferralFormIfApplicable As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusSpecialProgramReferralFormIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusSpecialProgramReferralFormIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateSpecialProgramReferralFormIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateSpecialProgramReferralFormIfApplicable As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHanoPreApplicationInitialApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHanoPreApplicationInitialApplication As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHanoPreApplicationInitialApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHanoPreApplicationInitialApplication As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHanoPreApplicationInitialApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHanoPreApplicationInitialApplication As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHanoPreApplicationInitialApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHanoPreApplicationInitialApplication As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHanoPreApplicationInitialApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHanoPreApplicationInitialApplication As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHanoPreApplicationInitialApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHanoPreApplicationInitialApplication As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeBriefingAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeBriefingAppointmentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeBriefingAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeBriefingAppointmentLetter As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerBriefingAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerBriefingAppointmentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerBriefingAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerBriefingAppointmentLetter As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusBriefingAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusBriefingAppointmentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateBriefingAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateBriefingAppointmentLetter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeScreeningAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeScreeningAppointmentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeScreeningAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeScreeningAppointmentLetter As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerScreeningAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerScreeningAppointmentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerScreeningAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerScreeningAppointmentLetter As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusScreeningAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusScreeningAppointmentLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateScreeningAppointmentLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateScreeningAppointmentLetter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeDocumentOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDocumentOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateDocumentOther As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateAuthorizationForReleaseOfInformationPrivacyActHud9886 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateAuthorizationForReleaseOfInformationPrivacyActHud9886 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHanoAuthorizationForReleaseOfInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHanoAuthorizationForReleaseOfInformation As Global.System.Web.UI.WebControls.Button
End Class
