'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateMoves

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnCompleteReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCompleteReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeVerification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerVerification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessVerification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeCalculation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerCalculation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessCalculation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypePaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypePaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypePaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypePaymentStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerPaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerPaymentStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusPaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessPaymentStandard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeUtilityAllowance As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUtilityAllowance As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessUtilityAllowance As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeTenantRent As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerTenantRent As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessTenantRent As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeOccupancyStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerOccupancyStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessOccupancyStandard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeMoves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeMoves As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeMoves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeMoves As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerMoves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerMoves As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerMoves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerMoves As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusMoves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusMoves As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessMoves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessMoves As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeChangeInFamilyComposition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeChangeInFamilyComposition As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerChangeInFamilyComposition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerChangeInFamilyComposition As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusChangeInFamilyComposition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessChangeInFamilyComposition As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeLeasing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeLeasing As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeLeasing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeLeasing As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerLeasing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerLeasing As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerLeasing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerLeasing As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusLeasing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLeasing As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessLeasing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessLeasing As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeDataEntry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDataEntry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessDataEntry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProcessOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProcessOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessOther As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHudInspectionChecklistFormHud52580 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHudInspectionChecklistFormHud52580 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHudInspectionChecklistFormHud52580 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHudInspectionChecklistFormHud52580 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHudInspectionChecklistFormHud52580 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHudInspectionChecklistFormHud52580 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHudInspectionChecklistFormHud52580 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHudInspectionChecklistFormHud52580 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHudInspectionChecklistFormHud52580 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHudInspectionChecklistFormHud52580 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHudInspectionChecklistFormHud52580 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHudInspectionChecklistFormHud52580 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHanoInspectionReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHanoInspectionReport As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHanoInspectionReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHanoInspectionReport As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHanoInspectionReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHanoInspectionReport As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHanoInspectionReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHanoInspectionReport As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHanoInspectionReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHanoInspectionReport As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHanoInspectionReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHanoInspectionReport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeInspectionOutcomeLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeInspectionOutcomeLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeInspectionOutcomeLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeInspectionOutcomeLetter As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerInspectionOutcomeLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerInspectionOutcomeLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerInspectionOutcomeLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerInspectionOutcomeLetter As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusInspectionOutcomeLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusInspectionOutcomeLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateInspectionOutcomeLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateInspectionOutcomeLetter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeAmenitiesReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeAmenitiesReport As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeAmenitiesReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeAmenitiesReport As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerAmenitiesReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerAmenitiesReport As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerAmenitiesReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerAmenitiesReport As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusAmenitiesReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusAmenitiesReport As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateAmenitiesReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateAmenitiesReport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeReasonableRentDeterminationCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeReasonableRentDeterminationCertification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeReasonableRentDeterminationCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeReasonableRentDeterminationCertification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerReasonableRentDeterminationCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerReasonableRentDeterminationCertification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerReasonableRentDeterminationCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerReasonableRentDeterminationCertification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusReasonableRentDeterminationCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusReasonableRentDeterminationCertification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateReasonableRentDeterminationCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateReasonableRentDeterminationCertification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeReasonableRentComparables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeReasonableRentComparables As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeReasonableRentComparables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeReasonableRentComparables As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerReasonableRentComparables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerReasonableRentComparables As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerReasonableRentComparables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerReasonableRentComparables As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusReasonableRentComparables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusReasonableRentComparables As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateReasonableRentComparables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateReasonableRentComparables As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentBurdenWorksheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentBurdenWorksheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeRentBurdenWorksheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeRentBurdenWorksheet As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentBurdenWorksheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentBurdenWorksheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRentBurdenWorksheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRentBurdenWorksheet As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentBurdenWorksheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentBurdenWorksheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRentBurdenWorksheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRentBurdenWorksheet As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeMasterLeasingChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeMasterLeasingChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerMasterLeasingChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerMasterLeasingChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusMasterLeasingChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateMasterLeasingChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateMasterLeasingChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeChecklistLeasingInspections As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeChecklistLeasingInspections As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerChecklistLeasingInspections As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerChecklistLeasingInspections As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusChecklistLeasingInspections As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateChecklistLeasingInspections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateChecklistLeasingInspections As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeLeasingPacketChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeLeasingPacketChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerLeasingPacketChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerLeasingPacketChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLeasingPacketChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateLeasingPacketChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateLeasingPacketChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeContractsExecutionChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeContractsExecutionChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerContractsExecutionChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerContractsExecutionChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusContractsExecutionChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateContractsExecutionChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateContractsExecutionChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeLease As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeLease As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerLease As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerLease As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLease As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateLease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateLease As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHapContract As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHapContract As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHapContract As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHapContract As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHapContract As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHapContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHapContract As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHudTenancyAddendum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHudTenancyAddendum As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHudTenancyAddendum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHudTenancyAddendum As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHudTenancyAddendum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHudTenancyAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHudTenancyAddendum As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRfta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeRfta As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRfta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRfta As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRfta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRfta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRfta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeSecurityDepositConfirmation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeSecurityDepositConfirmation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerSecurityDepositConfirmation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerSecurityDepositConfirmation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusSecurityDepositConfirmation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateSecurityDepositConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateSecurityDepositConfirmation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateImportantNoticeToOwnerAndTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateImportantNoticeToOwnerAndTenant As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHqsInspectionCertificationTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHqsInspectionCertificationTenant As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHqsInspectionCertificationOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHqsInspectionCertificationOwner As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateLeadBasedPaintDisclosureAndCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateLeadBasedPaintDisclosureAndCertification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHousingSearchLogIfApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHousingSearchLogIfApplicable As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeSignedOriginalVoucher As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeSignedOriginalVoucher As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerSignedOriginalVoucher As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerSignedOriginalVoucher As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusSignedOriginalVoucher As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateSignedOriginalVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateSignedOriginalVoucher As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDocumentOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDocumentOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateDocumentOther As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHapProcessingActionForm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlHapProcessingActionForm As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHapProcessingActionForm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHapProcessingActionForm As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHapProcessingActionForm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHapProcessingActionForm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentLetterTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentLetterTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentLetterTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRentLetterTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentLetterTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRentLetterTenant As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentLetterOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentLetterOwner As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentLetterOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRentLetterOwner As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentLetterOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRentLetterOwner As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlHudForm50058 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHudForm50058 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHudForm50058 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentCalculationSheet As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRentCalculationSheet As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRentCalculationSheet As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeLetterOfGoodStanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeLetterOfGoodStanding As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeLetterOfGoodStanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeLetterOfGoodStanding As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerLetterOfGoodStanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerLetterOfGoodStanding As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerLetterOfGoodStanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerLetterOfGoodStanding As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusLetterOfGoodStanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLetterOfGoodStanding As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateLetterOfGoodStanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateLetterOfGoodStanding As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeNoticeToVacateNoticeOfLeaseTermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeNoticeToVacateNoticeOfLeaseTermination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeNoticeToVacateNoticeOfLeaseTermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeNoticeToVacateNoticeOfLeaseTermination As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerNoticeToVacateNoticeOfLeaseTermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerNoticeToVacateNoticeOfLeaseTermination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerNoticeToVacateNoticeOfLeaseTermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerNoticeToVacateNoticeOfLeaseTermination As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusNoticeToVacateNoticeOfLeaseTermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusNoticeToVacateNoticeOfLeaseTermination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateNoticeToVacateNoticeOfLeaseTermination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateNoticeToVacateNoticeOfLeaseTermination As Global.System.Web.UI.WebControls.Button
End Class
