'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateSelectionFromWaitlist

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnCompleteReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCompleteReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLotteryNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLotteryNumber As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSpecialAdmission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSpecialAdmission As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPortIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPortIn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeOther6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeOther6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeOther6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeOther6 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerOther6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerOther6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerOther6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerOther6 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusOther6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusOther6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDocument6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDocument6 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeOtherSelectionFromTheWaitingListDocuments75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeOtherSelectionFromTheWaitingListDocuments75 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeOtherSelectionFromTheWaitingListDocuments75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeOtherSelectionFromTheWaitingListDocuments75 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerOtherSelectionFromTheWaitingListDocuments75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerOtherSelectionFromTheWaitingListDocuments75 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerOtherSelectionFromTheWaitingListDocuments75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerOtherSelectionFromTheWaitingListDocuments75 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusOtherSelectionFromTheWaitingListDocuments75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusOtherSelectionFromTheWaitingListDocuments75 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDocument75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDocument75 As Global.System.Web.UI.WebControls.Button
End Class
