'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateInterimReexamination

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnCompleteReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCompleteReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeVerification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerVerification As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusVerification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessVerification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeCalculation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerCalculation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusCalculation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessCalculation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypePaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypePaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypePaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypePaymentStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerPaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerPaymentStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusPaymentStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessPaymentStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessPaymentStandard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeUtilityAllowance As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUtilityAllowance As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUtilityAllowance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessUtilityAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessUtilityAllowance As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeTenantRent As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerTenantRent As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusTenantRent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessTenantRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessTenantRent As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeOccupancyStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerOccupancyStandard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusOccupancyStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessOccupancyStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessOccupancyStandard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeInterimReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeInterimReexamination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeInterimReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeInterimReexamination As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerInterimReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerInterimReexamination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerInterimReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerInterimReexamination As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusInterimReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusInterimReexamination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessInterimReexamination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessInterimReexamination As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeChangeInFamilyComposition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeChangeInFamilyComposition As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerChangeInFamilyComposition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerChangeInFamilyComposition As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusChangeInFamilyComposition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessChangeInFamilyComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessChangeInFamilyComposition As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeDataEntry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDataEntry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDataEntry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessDataEntry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeProcessOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerProcessOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusProcessOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcessOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcessOther As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateUtilityAllowanceChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateUtilityAllowanceChecklist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeNotes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeNotes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerNotes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerNotes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusNotes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateNotes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDocumentOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerDocumentOther As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDocumentOther As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateDocumentOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateDocumentOther As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHapProcessingActionForm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlHapProcessingActionForm As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHapProcessingActionForm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHapProcessingActionForm As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHapProcessingActionForm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHapProcessingActionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHapProcessingActionForm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentLetterTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentLetterTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentLetterTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRentLetterTenant As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentLetterTenant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRentLetterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRentLetterTenant As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentLetterOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentLetterOwner As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentLetterOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRentLetterOwner As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentLetterOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRentLetterOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRentLetterOwner As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlHudForm50058 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerHudForm50058 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHudForm50058 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateHudForm50058 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateHudForm50058 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentCalculationSheet As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerRentCalculationSheet As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentCalculationSheet As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateRentCalculationSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRentCalculationSheet As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateUaCalculationWorksheetElite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateUaCalculationWorksheetElite As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateApplicationForContinuedOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateApplicationForContinuedOccupancy As Global.System.Web.UI.WebControls.Button
End Class
