'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateReasonableRent

    '''<summary>
    '''btnCompleteReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCompleteReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeType13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeType13 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeType13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeType13 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManager13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManager13 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManager As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Status13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status13 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcess13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcess13 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeType21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeType21 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeType21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeType21 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManager21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManager21 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManager21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManager21 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Status21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status21 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcess21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcess21 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeType15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeType15 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeType15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeType15 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManager15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManager15 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManager15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManager15 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Status15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status15 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateProcess15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProcess15 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeAmenitiesReport1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeAmenitiesReport1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlAmenitiesReport1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlAmenitiesReport1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerAmenitiesReport1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerAmenitiesReport1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerAmenitiesReport1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerAmenitiesReport1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusAmenitiesReport1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusAmenitiesReport1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDocument1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDocument1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeReasonableRentDeterminationCertification7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeReasonableRentDeterminationCertification7 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlReasonableRentDeterminationCertification7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlReasonableRentDeterminationCertification7 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentDeterminationCertification7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentDeterminationCertification7 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentDeterminationCertification7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentDeterminationCertification7 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentDeterminationCertification7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentDeterminationCertification7 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDocument7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDocument7 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeReasonableRentComparables2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeReasonableRentComparables2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeReasonableRentComparables2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeReasonableRentComparables2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerReasonableRentComparables2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerReasonableRentComparables2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerReasonableRentComparables2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerReasonableRentComparables2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusReasonableRentComparables2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusReasonableRentComparables2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDocument2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDocument2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentBurdenWorksheet3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentBurdenWorksheet3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeRentBurdenWorksheet3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeRentBurdenWorksheet3 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentBurdenWorksheet3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentBurdenWorksheet3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentBurdenWorksheet3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentBurdenWorksheet3 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentBurdenWorksheet3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentBurdenWorksheet3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDocument3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDocument3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeRentIncreaseRequestFormIfApplicable4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeRentIncreaseRequestFormIfApplicable4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeRentIncreaseRequestFormIfApplicable4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeRentIncreaseRequestFormIfApplicable4 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerRentIncreaseRequestFormIfApplicable4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerRentIncreaseRequestFormIfApplicable4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRentIncreaseRequestFormIfApplicable4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRentIncreaseRequestFormIfApplicable4 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusRentIncreaseRequestFormIfApplicable4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRentIncreaseRequestFormIfApplicable4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDocument4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDocument4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeContractsExecutionChecklist5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeContractsExecutionChecklist5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeContractsExecutionChecklist5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeContractsExecutionChecklist5 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerContractsExecutionChecklist5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerContractsExecutionChecklist5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerContractsExecutionChecklist5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerContractsExecutionChecklist5 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusContractsExecutionChecklist5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusContractsExecutionChecklist5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDocument5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDocument5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NoticeTypeOther6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeOther6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlNoticeTypeOther6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNoticeTypeOther6 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CaseManagerOther6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseManagerOther6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManagerOther6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManagerOther6 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusOther6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusOther6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDocument6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDocument6 As Global.System.Web.UI.WebControls.Button
End Class
