'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditError

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Document control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Document As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDocumentTypeProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDocumentTypeProcess As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ProcessType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProcessType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlReviewTypeProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlReviewTypeProcess As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''NoticeTypeDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeDocument As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDocumentNoticeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDocumentNoticeType As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''NoticeTypeProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoticeTypeProcess As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlProcessNoticeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlProcessNoticeType As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''HousingSpecialistDropdownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HousingSpecialistDropdownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlCaseManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCaseManager As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatusDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''StatusHousingSpecialistDropdownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusHousingSpecialistDropdownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''statusComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents statusComplete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CompletionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompletionDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''CompletionApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompletionApproved As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnEditBasicError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditBasicError As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEditBasicBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditBasicBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEditLotteryNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditLotteryNumber As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEditLotteryNumberBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditLotteryNumberBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEditSpecialAdmission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditSpecialAdmission As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEditSpecialAdmissionBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditSpecialAdmissionBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEditPortIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditPortIn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEditPortInBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditPortInBack As Global.System.Web.UI.WebControls.Button
End Class
